config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :umbrellas  do
    collection do
      post :borrow
    end
  end

  resources :station do
    collection do
      post :return
    end
  end

  namespace :admin do
    resources :umbrellas
    resources :locations
    resources :users
  end

  scope :path => '/api/v1/', :module => "api_v1", :as => 'v1', :defaults => { :format => :json } do

    post "login" => "auth#login"
    post "logout" => "auth#logout"

    resources :umbrellas do
      collection do
        post :borrow
        get :list
      end
    end
  end

  root to: "umbrellas#index"
end

app/models/umbrella.rb
class Umbrella < ApplicationRecord
  belongs_to :umbrella_holder, :polymorphic => true
  belongs_to :enterprises, :optional => true

  has_many :umbrella_rent_histories
end

app/controllers/admin/umbrellas_controller.rb
class Admin::UmbrellasController < ApplicationController
  def index
    @locations = Location.all
    @umbrellas = Umbrella.all

    @umbrellas_in_renting = Umbrella.where(:umbrella_holder_type => :User)
    @umbrellas_in_station = Umbrella.where(:umbrella_holder_type => :Station)

    umbrella_rent_log = UmbrellaRentHistory.all

    station_time_log = {}

    umbrella_rent_log.each do |u|
      if u.start_location_id == 1
        station_time_log[u.start_time] = {:in => u.start_location_id}
      end
      if u.end_location_id == 1
        station_time_log[u.end_time] = {:out => u.end_location_id}
      end
    end

    @station_time_log = station_time_log.sort_by { |key, value| key }
  end

  def show
    umbrella = Umbrella.find(params[:id])
    @umb_log = umbrella.umbrella_rent_histories.order("id DESC")
  end
end

app/controllers/api_v1/umbrellas_controller.rb
class ApiV1::UmbrellasController < ApiController
  # before_action :authenticate_user!, :except => [:index, :list]
  # before_action :authenticate_user!
  # skip_before_filter :verify_authenticity_token

  def index
    @umbrella = Umbrella.all

    render :json => @umbrella, :except => [:created_at, :updated_at]
  end

  def show
    if current_user
      umbrella = current_user.umbrella
      render :json => umbrella, :except => [:created_at, :updated_at], :status => 200
    else
      render :json => { :errors => "you are not login" }
    end
  end

  def list
    umbrella_rent_log = UmbrellaRentHistory.all

    station_time_log = {}

    umbrella_rent_log.each do |u|
      station_time_log[u.start_time] = {:out => u.start_location_id}
      station_time_log[u.end_time] = {:in => u.end_location_id}
    end

    # station_time_log = station_time_log.sort_by { |key, value| key }

    render :json => station_time_log
  end

  def borrow
    if current_user
      umbrella = Umbrella.find(params[:id])
      umbrella.umbrella_holder = current_user

      if umbrella.save
        render :json => { :success => "all is well" }, :status => 200
      else
        render :json => { :errors => umbrella.errors.full_messages }
      end
    else
      render :json => { :errors => "you are not login" }
    end
  end
end

app/controllers/umbrellas_controller.rb
class UmbrellasController < ApplicationController
  before_action :authenticate_user!
  def index
    @umbrella = current_user.umbrella
    @my_umb_log = current_user.umbrella_rent_histories.order("id DESC")
  end

  def borrow
    umbrella = Umbrella.find(params[:id])

    umb_log = umbrella.umbrella_rent_histories.new
    umb_log.start_location = umbrella.umbrella_holder
    umb_log.start_time = Time.now()

    umbrella.umbrella_holder = current_user
    umb_log.user = umbrella.umbrella_holder

    if umbrella.save
      umb_log.save
    else
    end

    redirect_to umbrellas_path
  end
end

app/helpers/admin/umbrellas_helper.rb
module Admin::UmbrellasHelper
end

app/helpers/api_v1/umbrellas_helper.rb
module ApiV1::UmbrellasHelper
end

app/helpers/station/umbrellas_helper.rb
module Station::UmbrellasHelper
end

app/helpers/umbrellas_helper.rb
module UmbrellasHelper
end

app/views/umbrellas/index.html.erb
<h1>customer umbrella operation</h1>
<h4>scan an umbrella here</h4>

<h4>current umbrella</h4>
<% if @umbrella.nil? %>
  <%= form_tag borrow_umbrellas_path, :method => :post do %>
    <%= number_field_tag :id %>
    <%= submit_tag "借雨傘" %>
  <% end %>
<% else %>
  <p>目前借出的雨傘id：<%= @umbrella.id %></p>
<% end %>

<div class="container">
  <div class="row">
    <table class="table">
      <thead>
        <tr>
          <th class="text-center">id</th>
          <th class="text-center">起站</th>
          <th class="text-center">start time</th>
          <th class="text-center">迄站</th>
          <th class="text-center">end time</th>
          <th class="text-center">duration</th>
          <th class="text-center">金額</th>
        </tr>
      </thead>
      <tbody>
        <% @my_umb_log.each do |u| %>
          <tr>
            <td class="text-center"><%= u.id %></td>
            <td><%= u.start_location.name %></td>
            <td class="text-center"><%= distance_of_time_in_words(Time.now, u.start_time, include_seconds: true) %></td>
            <td><%= u.end_location.try(:name) %></td>
            <td class="text-center"><%= (distance_of_time_in_words(Time.now - u.end_time)) if u.end_time %></td>
            <td class="text-center"><%= (distance_of_time_in_words(u.end_time, u.start_time, include_seconds: true)) if u.end_time %></td>
            <td class="text-center"><%= u.amount %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>