config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :umbrellas  do
    collection do
      post :borrow
    end
  end

  resources :station do
    collection do
      post :return
    end
  end

  namespace :admin do
    resources :umbrellas
    resources :locations
    resources :users
  end

  scope :path => '/api/v1/', :module => "api_v1", :as => 'v1', :defaults => { :format => :json } do

    post "login" => "auth#login"
    post "logout" => "auth#logout"

    resources :umbrellas do
      collection do
        post :borrow
        get :list
      end
    end
  end

  root to: "umbrellas#index"
end

app/models/location.rb
class Location < ApplicationRecord
  has_many :umbrellas, :as => :umbrella_holder
end

app/controllers/admin/locations_controller.rb
class Admin::LocationsController < ApplicationController
  def index
    @locations = Location.all
    @umbrellas = Umbrella.all

    @umbrella_in_renting = Umbrella.where(:umbrella_holder_type => :User)

    umbrella_rent_log = UmbrellaRentHistory.all
    station_time_log = {}

    umbrella_rent_log.each do |u|
      if u.start_location_id == 1
        station_time_log[u.start_time] = {:in => u.start_location_id}
      end
      if u.end_location_id == 1
        station_time_log[u.end_time] = {:out => u.end_location_id}
      end
    end

    @station_time_log = station_time_log.sort_by { |key, value| key }
  end
  
end

app/helpers/admin/locations_helper.rb
module Admin::LocationsHelper
end

app/views/admin/locations/index.html.erb
<nav class="admin_umbrellas">
  <ul>
    <li>icon</li>
    <li><%= link_to "管理" %></li>
    <li><%= link_to "分析" %></li>
    <li class="right">
      <p>
        <%= link_to "#" do %> 
        <span class="glyphicon btn-glyphicon glyphicon-user img-circle text-muted"></span>
        <% end %>
      </p>
    </li>
    <li class="right"><%= link_to "登出" %></li>
  </ul> 
</nav>
<div class="row">
  <div class= "col-md-1">
    <div class="sidebar">
      <li>
        <%= link_to admin_locations_path do %> 
          <table>
            <tr>
              <td width=20% class="button_icon"><span class="glyphicon glyphicon-map-marker"></span></td>
              <td width=80% class="button_text">各站<br>資訊</td>
            </tr>
          </table>
        <% end %>
      </li>
      <li>
        <%= link_to admin_umbrellas_path do %> 
          <table>
            <tr>
              <td width=20% class="button_icon"><span class="glyphicon glyphicon-list-alt"></span></td>
              <td width=80% class="button_text">雨傘<br>清單</td>
            </tr>
          </table>
        <% end %>
      </li>
      <li>
        <%= link_to admin_users_path do %> 
          <table>
            <tr>
              <td width=20% class="button_icon"><span class="glyphicon glyphicon-search"></span></td>
              <td width=80% class="button_text">使用者<br>列表</td>
            </tr>
          </table>
        <% end %>
      </li>
    </div>
  </div>
  <div class="station col-md-11">
    <div class="line-switch">
      <li> <%= link_to "全線" %> </li> 
      <li> <%= link_to "文湖線" %></p> </li> 
      <li> <%= link_to "淡水信義線" %> </li> 
      <li> <%= link_to "松山新店線" %> </li> 
      <li> <%= link_to "中和新蘆線" %> </li> 
      <li> <%= link_to "板南線" %> </li> 
      <li> <%= link_to "借出中" %> </li> 
    </div>
    <div class="data-editor col-md-12">
      <li class="right">
        <div>
          <p>
            <%= link_to "#" do %> 
            <span class="glyphicon btn-glyphicon glyphicon-pencil img-circle text-muted"></span>
            <% end %>
          </p>
        </div>
      </li>
      <li class="right">
        <div class="circle">
          <p>
            <%= link_to "#" do %> 
            <span class="glyphicon btn-glyphicon glyphicon-plus img-circle text-muted"></span>
            <% end %>
          </p>
        </div>
      </li>
    </div>
    <% @locations.each do |location| %>
    <div class="location_container col-lg-2">
      <div class="location_info ">
        <p class="location_id"> <%= location.id %>  </p>
        <p class="location_name"> <%= location.name %>  </p>
        <p class="location_description"> <%= location.description %>  </p>
        <br>
        <p class="location_umbrella_number"> "可租雨傘數"<%= location.umbrellas.size %>  </p>
      </div>
    </div>
    <% end %>
  </div>
</div>

===== paginate =====