config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :umbrellas  do
    collection do
      post :borrow
    end
  end

  resources :station do
    collection do
      post :return
    end
  end

  namespace :admin do
    resources :umbrellas
    resources :locations
    resources :users
  end

  scope :path => '/api/v1/', :module => "api_v1", :as => 'v1', :defaults => { :format => :json } do

    post "login" => "auth#login"
    post "logout" => "auth#logout"

    resources :umbrellas do
      collection do
        post :borrow
        get :list
      end
    end
  end

  root to: "umbrellas#index"
end

app/controllers/station_controller.rb
class StationController < ApplicationController
  def show
    @station = Location.find(params[:id])
    @umbrellas = @station.umbrellas
  end

  def return
    umbrella = Umbrella.find(params[:id])
    current_location = Location.find(params[:location_id])
    umbrella.umbrella_holder = current_location

    umb_log = umbrella.umbrella_rent_histories.last
    umb_log.end_location = umbrella.umbrella_holder
    umb_log.end_time = Time.now()

    if umbrella.save
      umb_log.save
    else
    end

    redirect_to station_path(params[:location_id])
  end
end

app/helpers/station/umbrellas_helper.rb
module Station::UmbrellasHelper
end

app/helpers/station_helper.rb
module StationHelper
end

app/views/station/show.html.erb
<h1>Station:<%= @station.name %></h1>

<table>
  <thead>
    <tr>
      <th>id</th>
      <th>進站時間</th>
    </tr>
  </thead>
  <tbody>
    <% @umbrellas.each do |umbrella| %>
      <tr>
        <td><%= umbrella.id %></td>
        <td><%= umbrella.updated_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

  <%= form_tag return_station_index_path(:location_id => params[:id]), :method => :post do %>
    <%= number_field_tag :id %>
    <%= submit_tag "歸還雨傘" %>
  <% end %>